package com.kumuda.bookshopandroid.constants

class Constants {
    companion object {
        const  val CART_LIST="CART_LIST"
        val ADD_SCHOOL: Int = 100
        var SOURCE = "source"
        var DIALOGUE_BOX = "Dialogue Box"
        var REASON = "Reason"
        const val SPLASH_SCREEN = "Splash screen"
        const val ORDER_id= "OrderID"

        const val status = "status"
        const val message = "message"

        const val SUCCESS = "SUCCESS"
        const val CANCELLED = "Cancelled"
        const val PENDING = "Pending"
        const val PLACED = "Placed"

        const val RES_SUCCESS = "success"
        const val RES_FAILED = "failed"

        //SCREENS
        const val HOME = "HOME"
        const val SCHOOL="SCHOOL"
        const val BEFORE_SEL="BEFORE_SEL"
        const val AFTER_SEL="AFTER_SEL"
        const val CLASS_LIST="CLASS_LIST"
        const val BUNDLE="BUNDLE"
        const val CART="CART"
        const val ORDER="ORDER"
        const val ORDER_DETAIL="ORDER_DETAIL"
        const val CHECK_OUT="CHECK_OUT"
        const val SubBaseActivity="SubBaseActivity"
        const val LOGIN="LOGIN"
        const val REGISTRATION="REGISTRATION"
        const val PAYMENT="PAYMENT"
        const val NOTIFICATION="NOTIFICATION"
        const val MY_PROFILE="MY_PROFILE"
        const val SCHOOL_ID="SCHOOL_ID"
        const val Change_password="Change_password"

        const val TokenID = "TokenID"
        const val _SESION = "_session"
        const val ADD_TO_CART = "ADD_TO_CART"
        const val REMOVE_FROM_CART = "REMOVE_FROM_CART"
        const val JWT_TOKEN = "JWT_TOKEN id"
        const val IS_USER_LOGIN = "isUserLogin"
        const val LANDING_SCREEN = "Landing screen"
        const val DELIVERY_TYPE_SELECTION= "Delivery selection"
        const val DELIVERY_SELCTED_TIME_SLOT= "Delivery Time slot"
        const val TYPE_NOTIFICATION_ADAPTER = "Notification Adapter"
        const val TYPE_SCHOOL_LIST_ADAPTER = "School List Adapter"
        const val TYPE_CLASS_LIST_ADAPTER = "Class List Adapter"
        const val TYPE_BUNDLE_LIST_ADAPTER = "CartModel List Adapter"
        const val TYPE_CART_LIST_ADAPTER = "Cart List Adapter"
        const val TYPE_ORDER_LIST_ADAPTER = "Order List Adapter"
        const val TYPE_ORDER_DETAIL_LIST_ADAPTER = "Order Detail List Adapter"
        const val DELETE_CONFIRMATION = "delete confirmation"
        const val ORDER_CANCELLED_CONFIRMATION = "cancel order2 confirmation"
        const val ORDER_RETURNED_CONFIRMATION = "return order2 confirmation"
        const val SELECTED_CHECK_BOX = "SELECTED_CHECK_BOX"
        const val MY_ORDERD_LIST = "MY_ORDERD_LIST"
        val SOURCE_School = "SOURCE_School"
        val REGISTRATION_SOURCE = "REGISTRATION_SOURCE"
        const val CUR_CUSTOMER = "customer "

        const val email = "email"
        const val mobileNumber = "MobileNumber"
        const val MobileNumber = "MobileNumber"
        const val password = "Password"

        const val EMAIL = "email"
        const val PASSWORD = "PASSWORD"
        const val OTP = "otp"
        const val CUSTOMER_ID = "_id"
        const val FIRST_NAME = "first_name"
        const val MOBILE = "mobile"
        const val DELIVERY_ADDRESS = "delivery address"
        const val AUTHORIZATION = "AUTHORIZATION"
        const val OTP_ = "OTP"

        const val PROFILE_ID = "PROFILE_ID"
        const val PROFILE_NAME = "PROFILE_NAME"
        const val TOKEN_ID = "TOKEN_ID"

        const val OrderID = "OrderID"

        //Profile Detail
        const val ProfileID = "ProfileID"
        const val ProfileName = "ProfileName"
        const val SchoolID = "SchoolID"
        const val ClassID = "ClassID"
        const val LastNotificationID = "LastNotificationID"
        const val LastOrderID = "LastOrderID"
        const val Address1 = "Address1"
        const val Address2 = "Address2"
        const val City = "City"
        const val EmailAddress = "EmailAddress"
        const val IsEmailVerified = "IsEmailVerified"
        const val PostalCode = "PostalCode"
        const val State = "State"
        const val PackageID = "PackageID"
        const val Quantity = "Quantity"
    }
}